### ISSUE TITLE
Cannot see dynamically added fields in model

### ISSUE THREAD

**Issue by slyadams** [OptimalBPM/angular-schema-form-complex-ui#1]
When adding properties to an "object" type using a controller method, I cannot see those fields appearing in the model.

Plunker: https://plnkr.co/edit/gWrGzlCnalO9Y69aB0VQ?p=info

**Comment by nicklasb** [comment]
You seem to be right, the main model isn't updated. I do not use that feature in my system currently, so I have failed to notice this.

**Comment by nicklasb** [comment]
Ok, so this is actually _not_ a bug. Sort of.
The reason is that the model has to be initiated with that field. If it isn't, it cannot be linked to by the component. 
The component can't nicely initiate it by itself as ASF uses a $$value$$ string replace thing to give it a reference which works with conventional fields, but may be problematic with objects. 
From 1.0, ASF will not use the same method, so perhaps that will work better then.
See if this works for you.

**Comment by nicklasb** [comment]
I added initiation of the model in the example.

**Comment by slyadams** [comment]
Seems to do the trick, I guess this means if the base schema you're loading isn't known to you (e.g. external JSON), you'll need to scan it and initialize the fields in the model accordingly.

**Comment by nicklasb** [comment]
Well, not all fields, just the main object, right?

**Comment by nicklasb** [comment]
And only for each schema you load.

**Comment by nicklasb** [comment]
If you find a way for the component to initiate itself, I would love a PR to that end. :-)
